"""add_lesson_lang

Revision ID: 4ddd2e14d1f6
Revises: 7ecbebe06d5b
Create Date: 2024-08-26 20:09:13.413299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ddd2e14d1f6'
down_revision: Union[str, None] = '7ecbebe06d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('language', sa.String(), nullable=True))
    op.add_column('lessons', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'is_available')
    op.drop_column('lessons', 'language')
    # ### end Alembic commands ###
